import Head from 'next/head'
import { Scrollama, Step } from 'react-scrollama';
import { useSpring, animated } from '@react-spring/web';
import { Text } from '@nextui-org/react';
import TextCard from "../components/TextCard";
import styles from '../styles/Home.module.css'
import TinyCrossfade from "react-tiny-crossfade";

import BackgroundOne from "../components/Scrollama/BackgroundOne";
import BackgroundTwo from "../components/Scrollama/BackgroundTwo";
import {useState} from "react";

export default function Home() {
  let [backgroundContent, setBackgroundContent] = useState(null);

  const onStepEnter = ({ data }) => {
    console.log('enter', data)
    // Set the children of the div with id "background-display" to the data passed in from the Step component
    if (data === 1) {
      setBackgroundContent(BackgroundOne);
    } else if (data === 2) {
      setBackgroundContent(BackgroundTwo);
    }
  };

  const onStepExit = ({ data }) => {
    console.log('exit', data)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Blah</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/crs6xwd.css" />
      </Head>

      <main className={styles.main}>
        <TinyCrossfade
          classNames={
            {
              beforeEnter: "opacity-0 duration-500",
              entering: "opacity-100 duration-500",
              beforeLeave: "opacity-100 duration-500",
              leaving: "opacity-0 duration-500"
            }
          }
          className={""}
        >
          <div className="fixed top-0 left-0 w-full h-full z-0" id={"background-display"}>
            {backgroundContent}
        </div>
        </TinyCrossfade>


        <div className={"absolute z-10 top-0 pointer-events-none"}>
          <div className={"flex flex-col items-center w-full h-full"}>
            <Scrollama onStepEnter={onStepEnter} onStepExit={onStepExit} offset={0.5}>
              <Step data={1}>
                <div>
                <TextCard>
                  <h1 className={styles.textCardTitle}>Introduction</h1>
                  <p className={styles.textCardBody}>
                    The first day I discovered ChatGPT, I was really in shock. I had already known about the year’s AI advances, but this
                    was something new altogether.
                  </p>
                </TextCard>
                </div>
              </Step>
              <Step data={1}>
                <div>
                  <TextCard>
                    <p className={styles.textCardBody}>I was almost surprised to learn that the text generation was actually done by many GPUs in a data center rather than by
                      a human, because at first, it sure felt like a person was at the other end of the conversation. It was so different from
                      GPT-3 and other text generation models -- it was so uncanny.</p>
                  </TextCard>
                </div>
              </Step>
              <Step data={2}>
                <div>
                  <TextCard>
                    <p className={styles.textCardBody}>After my initial surprise, I quickly started pushing the limits of the system and its generative abilities.
                      It became clear that its human-like speech wasn’t so human-like after all. But these developments raised important
                      questions in my mind about how AI changes our understanding of ourselves and our relationships with the world.</p>
                  </TextCard>
                </div>
              </Step>
            </Scrollama>
          </div>
        </div>
      </main>
    </div>
  )
}
